### ISSUE TITLE
how can i call bitrate function

### ISSUE THREAD

**Issue by Rishabh-Maheshwari** [rabitt/pysox#84]

**Comment by lostanlen** [comment]
Hello. There is currently a bug in pysox (#68) that causes `pysox.file_info.bitrate` to return the bit depth rather than the bit rate. I wrote a fix to that bug in PR #75. This PR passed code review, continuous integration, and tests, so it is ready for merging. However, it mightl be a while before the admin @rabitt merges it and makes it into pysox v1.4. Consequently, you need to clone my `patch-1` branch and import it locally rather than installing pysox through pip.
https://github.com/lostanlen/pysox/tree/patch-1

I hope this helps!
